server:
  port: 8081
  shutdown: graceful
management:
  endpoints:
     web:
       exposure:
         include: '*'
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  info:
     git:
       mode: full
######## Database Configuration  #########
spring:
  application:
    name : catalog-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: false


######## Catalog Service Configuration  #########
catalog:
  page-size: 10

swagger:
  api-gateway-url: http://localhost:8989/catalog